### ISSUE TITLE
bug like

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/tinysocial#12]
when a message does not like: 
an error appears

I can like the same message to infinity

**Comment by mitchellurgero** [comment]
Does it actually like infinitly? Because if an error occures it's not supposed to like the post.

**Comment by simon511000** [comment]
I currently have big problems with internet connection.
So I can not upload screenshots, so can you try his site? http://simon511000.fr/tinysocial/

**Comment by simon511000** [comment]
Ah! I just got it !
On messages that were created before the update, we can like to infinity, for against the messages that were created after the update, I have the error message when I like twice .
Excuse me.... 💯 💯

**Comment by mitchellurgero** [comment]
Nice nice. Good shot, also good hosting ;)
