### ISSUE TITLE
Version number script errors on Windows installation

### ISSUE THREAD

**Issue by rbertram90** [mitchellurgero/tinysocial#3]
'wc' command is specific to Linux, so version number is just an empty array on Windows install

`exec('git rev-list HEAD | wc -l',$version_number);`

(app/includes.php line 69)

**Comment by mitchellurgero** [comment]
You can install Apache in Windows or use a VM. I can’t officially support Windows right now, sorry :/

**Comment by mitchellurgero** [comment]
I am going to close this since I do not have plans to support windows, but if you fork and make a pull request I'll add it.
