### ISSUE TITLE
Traduction française !

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/tinysocial#4]
Je viens de faire la traduction français de tinysocial.

Enjoy !

**Comment by mitchellurgero** [comment]
Hey very nice! If you dork my repo, add your file, then submit pull request :)

**Comment by simon511000** [comment]
I'm sorry, but how to submit pull request ?

**Comment by simon511000** [comment]
ok, I think I found

**Comment by mitchellurgero** [comment]
Good job! Merged now :)
